"""empty message

Revision ID: 5ab9f323e451
Revises: 
Create Date: 2025-10-02 19:07:32.169643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab9f323e451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('prediction',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_table('patient_anamnesis',
    sa.Column('anamnesis_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anamnesis_id'),
    sa.UniqueConstraint('anamnesis_id')
    )
    with op.batch_alter_table('patient_anamnesis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_anamnesis_patient_id'), ['patient_id'], unique=False)

    op.create_table('visit',
    sa.Column('visit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('visit_id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.visit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('prediction_visit',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.prediction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.visit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id', 'visit_id')
    )
    op.create_table('record',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.visit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('prediction_visit')
    op.drop_table('event')
    op.drop_table('visit')
    with op.batch_alter_table('patient_anamnesis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_anamnesis_patient_id'))

    op.drop_table('patient_anamnesis')
    op.drop_table('prediction')
    op.drop_table('patient')
    # ### end Alembic commands ###
